apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-boot-api-versioning
  labels: 
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-boot-api-versioning
spec:
  env:
    - name: SPRING_DATA_MONGODB_HOST
      value: api-versioning-db-mongodb
    - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
      value: api-versioning
    - name: SPRING_DATA_MONGODB_DATABASE
      value: api-versioning
    - name: SPRING_DATA_MONGODB_USERNAME
      value: api-versioning
    - name: SPRING_DATA_MONGODB_PASSWORD
      value: test1234
  source:
    git:
      url: git@github.com:mathias-ewald/spring-boot-api-versioning.git
      ref:
        branch: main