server:
    forward-headers-strategy: NATIVE

spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: api-versioning
    jackson:
        serialization:
            indent_output: true

mongock:
    migration-scan-package:
        - com.example.versioning.data.migrations